package streamExample.agent.ui;

import java.awt.Dimension;
import javax.swing.JMenu;
import javax.swing.JPanel;

/**
 * JFrame window for stream clients and servers. 
 */
public class StreamDisplayFrame extends javax.swing.JFrame {

    protected Dimension dimension;
    
    /**
     * Creates new form StreamClientDisplayWindow
     */
    public StreamDisplayFrame() {
        initComponents();
        
    }
    
    public StreamDisplayFrame(String name) {
        this();
        this.setName(name);
    }
    
    public void addVideoPanel(JPanel videoPanel) {
        this.videoContentPanel.removeAll();
        this.videoContentPanel.add(videoPanel);
    }
    
    public void addInfoPanel(JPanel infoPanel) {
        this.infoContentPanel.add(infoPanel);
    }
    
    public void addMenu(JMenu menu) {
        this.menuBar.add(menu);
        this.menuBar.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoContentPanel = new javax.swing.JPanel();
        videoContentPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(320, 300));
        setName(""); // NOI18N
        setResizable(false);

        infoContentPanel.setBackground(java.awt.SystemColor.window);
        infoContentPanel.setMinimumSize(new java.awt.Dimension(320, 35));
        infoContentPanel.setPreferredSize(new java.awt.Dimension(320, 35));
        infoContentPanel.setLayout(new java.awt.GridLayout(1, 0, 1, 0));

        videoContentPanel.setBackground(java.awt.Color.gray);
        videoContentPanel.setMinimumSize(new java.awt.Dimension(320, 240));
        videoContentPanel.setPreferredSize(new java.awt.Dimension(320, 240));
        videoContentPanel.setLayout(new java.awt.GridLayout(1, 1));

        menuBar.setMinimumSize(new java.awt.Dimension(320, 25));
        menuBar.setPreferredSize(new java.awt.Dimension(320, 25));
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(infoContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(videoContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(infoContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 240, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 35, Short.MAX_VALUE)
                    .addComponent(videoContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel infoContentPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel videoContentPanel;
    // End of variables declaration//GEN-END:variables
}
