package streamExample.agent.ui.components;

/**
 * Information display panel for stream client.
 */
public class StreamClientInfoPanel extends javax.swing.JPanel {

    public StreamClientInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HostLabel = new javax.swing.JLabel();
        PortLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        HostEditableLabel = new javax.swing.JLabel();
        PortEditableLabel = new javax.swing.JLabel();
        StatusEditableLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(320, 35));
        setPreferredSize(new java.awt.Dimension(320, 35));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new java.awt.GridLayout(2, 3));

        HostLabel.setText("Host:");
        add(HostLabel);

        PortLabel.setText("Port:");
        add(PortLabel);

        StatusLabel.setText("Stan:");
        add(StatusLabel);

        HostEditableLabel.setText("-");
        add(HostEditableLabel);

        PortEditableLabel.setText("-");
        add(PortEditableLabel);

        StatusEditableLabel.setText("Rozłączony");
        add(StatusEditableLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HostEditableLabel;
    private javax.swing.JLabel HostLabel;
    private javax.swing.JLabel PortEditableLabel;
    private javax.swing.JLabel PortLabel;
    private javax.swing.JLabel StatusEditableLabel;
    private javax.swing.JLabel StatusLabel;
    // End of variables declaration//GEN-END:variables
}
